# Generated by Django 2.1.2 on 2019-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_board',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(max_length=4)),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'todo_list',
                'managed': False,
            },
        ),
    ]
